openapi: 3.0.0
info:
  version: v20.5.25
  title: SplittyPay Integration
  contact:
    email: support@parque.email
    name: Parque
  x-logo:
    url: 'https://i.ibb.co/r5679FD/pulsee-2.png'

  description: >
    # Introduction

    This project is a built-in payment method for Pulsee app.


    Thanks to SplittyPay technology it will be possible to split the entire amount of Pulsee invoice
    among all people involved in Pulsee service (contributors)
    instead of delegate payment for the entire amount to people who have been registered into Pulsee service contract (account-holder).

    # API

    These RESTful API offers all features to handle Customers, their Contracts and relatives Invoices.

tags:
  - name: Customer
    description: Everything about Customer
  - name: Contract
    description: Everything about Contract
  - name: Invoice
    description: Everything about Invoice

servers:
  - url: pulsee.splittypay.it

paths:
  /customers:
    $ref: './customers/customers.yaml#/paths/~1customers'
  /customers/{id}:
    $ref: './customers/customers.yaml#/paths/~1customers~1{id}'

  /contracts:
    $ref: './contracts/contracts.yaml#/paths/~1contracts'
  /contracts/{id}:
    $ref: './contracts/contracts.yaml#/paths/~1contracts~1{id}'

  /invoices:
    $ref: './invoices/invoice.yaml#/paths/~1invoices'
  /invoices/{id}:
    $ref: './invoices/invoice.yaml#/paths/~1invoices~1{id}'

components:
  securitySchemes:
    basic_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://example.com/api/oauth/dialog
          scopes:
            user: user permission
            company: company permission
    api_key:
      type: apiKey
      in: header
      name: api_key
